### ISSUE TITLE
fonts with shadow are not properly displayed in minimap...

### ISSUE THREAD

**Issue by masavini** [robatron/atom-figletify#1]
hi,
i found that "ANSI Shadow" is my favourite figlet font.
when used, however, the minimap plugin shows unreadable chars, as the font shadow is printed by minimap as well.

i solved with a quick and dirty:

``` coffee
   art = art.replace /[\u2550-\u255D]/g, " "
```

in the end of `~/.atom/packages/figletify/lib/figletify.coffee`, but i guess a settings option like "remove shadow" would be better...

**Comment by robatron** [comment]
In a long meeting, so I figured I'd *finally* address these issues :-P

I just tried the "ANSI Shadow" font with the latest version of [minimap](https://atom.io/packages/minimap), and figletified text appears to be rendering correctly:

![screen shot 2016-12-02 at 10 35 07 am](https://cloud.githubusercontent.com/assets/127095/20845688/1b2bf12e-b87b-11e6-838a-670ee930f320.png)

Seems like this is no longer an issue. Let me know if that's not the case.
